import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '../components/Navbar.jsx'
import Footer from '../components/Footer.jsx'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" bg-gradient-to-r from-gray-400  to-gray-500">
          <NavBar />
          {children} <Footer />
        </div>
      </body>
    </html>
  )
}
